#!/usr/bin/env bash
# Bash script to Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get -y install haproxy
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo echo "
frontend http
    bind *:80
    mode http
    default_backend back
backend back
    balance roundrobin
    server gc-1881-web-01-1607550953 35.185.80.75:80 check
    server gc-1881-web-02-1608528490 35.231.48.2:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart

