#!/usr/bin/env bash
# Script using while loop to displays Holberton Shcool 10 times

c=0
while [ $c -le 9 ]
do
	echo "Holberton School"
	((c++))
done

#i=0
#while ((i < 10));
#do
#	echo "Holberton School"
#	i=$((i + 1))
#done
