#!/usr/bin/env bash
# Script to displays Holberton Shcool 10 times and hi in the 9 iteration using while loop

c=1
while [ $c -le 10 ]
do
	if [ $c = 9 ]
	then
		echo "hi"
	else
		echo "Holberton School"
	fi
	((c++))

done
