#!/usr/bin/env bash
# Script that gives info about holbertonschool file

f=holbertonschool
if [ -e $f ]
then
	echo "holbertonschool file exists"
	if [ ! -s $f ]
	then
		echo "holbertonschool file is empty"
	else
		echo "holbertonschool file is not empty"
	fi
	if [ -f $f ]
	then
		echo "holbertonschool is a regular file"
	else
		echo ""
	fi
else
	echo "holbertonschool file does not exist"
fi
