#!/usr/bin/env bash
# Bash script that configures the container to nginx as user
pkill -f apache2
chmod 700 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx nginx
sudo -u nginx service nginx start

